all: restart

restart:
	brew services restart sketchybar

stop:
	brew services stop sketchybar

start:
	brew services start sketchybar

upgrade:
	brew services stop sketchybar
	brew upgrade sketchybar
	brew services start sketchybar