#!/usr/bin/env sh

# Here we refer to the wiki of yabai. The specific steps are described below
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Window layout bsp: tile float: float
yabai -m config layout                       bsp
# Default split rule first_child second_child
yabai -m config window_placement             second_child
# Window spacing settings
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2
# Auto balance all windows always occupy the same space
yabai -m config auto_balance                 off
# If auto balancing is disabled, this property defines the amount of space occupied by the new window. 0.5 means that the old window occupies 50%
yabai -m config split_ratio                 0.50
# The mouse modifier button means that you can use the mouse to modify the window size alone by pressing this button
yabai -m config mouse_modifier               fn
# fn + left key movement
yabai -m config mouse_action1                move
# fn + right click
yabai -m config mouse_action2                resize
# Focus follow mouse default off: turn off autoraise: Auto Lift autofocus: Auto Focus
# yabai -m config focus_follows_mouse          autofocus
# Sets whether the mouse follows the current active window. The default is off: off: on: on
# yabai -m config mouse_follows_focus          on

# Floating window problem at the top
yabai -m config window_topmost               on
# Modify window shadow on: open off: close float: only show the shadow of floating window
yabai -m config window_shadow                float

# Window transparency settings
yabai -m config window_opacity               on
# Configure the opacity of the active window
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1 # 0.9
yabai -m config window_opacity_duration      0.0

# Add 20 padding at the top and 0 padding at the bottom of each space on the main display
# yabai -m config external_bar main:20:0
# Add a 0 fill at the top and a 0 fill at the bottom of each space on all displays
# yabai -m config external_bar all:0:5

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:20:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:20:20

SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:30:0
# yabai -m config external_bar all:49:0
# yabai -m config ext ernal_bar all:0:0


# ================================Rules================================
# Turn on System Preferences without using tile mode
# yabai -m rule --add app="^System Preferences $" manage=off
# yabai -m rule --add app="^Reminders $" manage=off
# yabai -m rule --add app="^About this machine $" manage=off

yabai -m rule --add app="^(LuLu|Vimac|Calculator|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice)$" manage=off

# ===== Rules ==================================

yabai -m rule --add label="Steam" app="^Steam$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Alfred" app="^Alfred$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off


# yabai -m signal --add event=window_created action="sketchybar -m --trigger window_created &> /dev/null"
# yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_destroyed &> /dev/null"
# yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"

# yabai -m space 1 --label code
# yabai -m space 2 --label tex
# yabai -m space 3 --label web
# yabai -m space 4 --label idle
# yabai -m space 5 --label misc
# yabai -m space 6 --label doc
# yabai -m space 7 --label help
# yabai -m space 8 --label music

yabai -m config window_border on
yabai -m config window_border_width 4
yabai -m config active_window_border_color 0xFF329bff #https://encycolorpedia.com/46ccff
yabai -m config normal_window_border_color 0x00FFFFFF # 00 = zero brightness FF = full brightness | color
yabai -m config insert_feedback_color        0xffd75f5f

echo "yabai configuration loaded.."