all: restart

restart:
	brew services restart spacebar

stop:
	brew services stop spacebar

start:
	brew services start spacebar

upgrade:
	brew services stop spacebar
	brew upgrade spacebar
	brew services start spacebar